version: '3.9'

services:
  postgres:
    container_name: workout_postgres_container
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "workoutdb"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: