package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"
	"workout-training-api/internal/graphql/graph/model"
)

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, email string, password string) (*model.SignInResp, error) {
	panic(fmt.Errorf("not implemented: SignIn - signIn"))
}

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, email string, password string) (*model.SignUpResp, error) {
	panic(fmt.Errorf("not implemented: SignUp - signUp"))
}
