// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
)

func (ec *executionContext) unmarshalNWorkout(ctx context.Context, v any) (model.Workout, error) {
	var res model.Workout
	err := res.UnmarshalGQL(v)
	return res, graphql.ErrorOnPath(ctx, err)
}

func (ec *executionContext) marshalNWorkout(ctx context.Context, sel ast.SelectionSet, v model.Workout) graphql.Marshaler {
	return v
}
